### ISSUE TITLE
Help the train_lmdb and test_lmdb!

### ISSUE THREAD

**Issue by getengqing** [rricard/caffeface#1]
Hello! How can I get the  facenet_train_test.prototxt files of train_lmdb and test_lmdb?

**Comment by saladin0786** [comment]
that is what I wondered..

**Comment by rricard** [comment]
I don't maintain this project. Sorry.

**Comment by saladin0786** [comment]
Oh, ok... thanks anyway ...!

**Comment by rricard** [comment]
Yes I'm sorry, I had to use caffe for a school project, never really worked. However, you should use tensorflow or theano with which I had good results (can't show you though ..)

**Comment by saladin0786** [comment]
Oh, thanks for your advice ..! I didn't expect that you would reply me
though :) I'm sincerely thanks to you from Korea. Ofcourse South !

**Comment by rricard** [comment]
Tip: use keras, it is really cool: http://keras.io/

**Comment by saladin0786** [comment]
Omg, I appreciate it ..! It looks cool. Thanks !
